# Generated by Django 3.2.9 on 2021-11-30 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_animalimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Animal', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
