# Generated by Django 3.2.9 on 2021-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_animalimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalimage',
            name='file_type',
            field=models.CharField(default='jpg', max_length=10),
        ),
    ]
